{"uuid": "b5821b1b-8825-459e-88bf-ffc040fefdd7", "children": ["6ba819ac-6d1b-4405-af49-0021e75a5bcb"], "befores": [{"name": "login", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSelectorException: Message: invalid selector: Unable to locate an element with the xpath expression //*[@id='app']div[1]/div[1]/div/div/div[3]/div[1]/div/span because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='app']div[1]/div[1]/div/div/div[3]/div[1]/div/span' is not a valid XPath expression.\n  (Session info: chrome=83.0.4103.116)\n\n", "trace": "  File \"/Users/wangziqing/venv/lib/python3.7/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/wangziqing/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/wangziqing/venv/lib/python3.7/site-packages/_pytest/fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"/Users/wangziqing/PycharmProjects/ui自动化/testcase/conftest.py\", line 25, in login\n    user=driver.get_text(el['username'])\n  File \"/Users/wangziqing/PycharmProjects/ui自动化/utils/ui.py\", line 254, in get_text\n    el = self.get_element(css)\n  File \"/Users/wangziqing/PycharmProjects/ui自动化/utils/ui.py\", line 93, in get_element\n    element = self.driver.find_element_by_xpath(value)  # 如果是xpath要以此格式传入xpath=>//*[@id='su']\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 394, in find_element_by_xpath\n    return self.find_element(by=By.XPATH, value=xpath)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "登录", "source": "ebd1ced8-ecfb-49fd-8d6b-36e93cc19507-attachment.attach"}], "start": 1595073469313, "stop": 1595073479048}], "start": 1595073469313, "stop": 1595073479174}